In [61]:
import datasets
import random
import pandas as pd
import numpy as np
from itertools import chain

In [7]:
dataset = datasets.load_dataset("squad")

dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'title', 'context', 'question', 'answers'],
        num_rows: 87599
    })
    validation: Dataset({
        features: ['id', 'title', 'context', 'question', 'answers'],
        num_rows: 10570
    })
})

In [8]:
eval_dataset = dataset["validation"]

eval_dataset

Dataset({
    features: ['id', 'title', 'context', 'question', 'answers'],
    num_rows: 10570
})

In [9]:
eval_dataset = pd.DataFrame(eval_dataset)

eval_dataset

,id,title,context,question,answers
0,56be4db0acb8001400a502ec,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team represented the AFC at Super Bo...,"{'text': ['Denver Broncos', 'Denver Broncos', ..."
1,56be4db0acb8001400a502ed,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team represented the NFC at Super Bo...,"{'text': ['Carolina Panthers', 'Carolina Panth..."
2,56be4db0acb8001400a502ee,Super_Bowl_50,Super Bowl 50 was an American football game to...,Where did Super Bowl 50 take place?,"{'text': ['Santa Clara, California', 'Levi's S..."
3,56be4db0acb8001400a502ef,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team won Super Bowl 50?,"{'text': ['Denver Broncos', 'Denver Broncos', ..."
4,56be4db0acb8001400a502f0,Super_Bowl_50,Super Bowl 50 was an American football game to...,What color was used to emphasize the 50th anni...,"{'text': ['gold', 'gold', 'gold'], 'answer_sta..."
...,...,...,...,...,...
10565,5737aafd1c456719005744fb,Force,"The pound-force has a metric counterpart, less...",What is the metric term less used than the New...,"{'text': ['kilogram-force', 'pound-force', 'ki..."
10566,5737aafd1c456719005744fc,Force,"The pound-force has a metric counterpart, less...",What is the kilogram-force sometimes reffered ...,"{'text': ['kilopond', 'kilopond', 'kilopond', ..."
10567,5737aafd1c456719005744fd,Force,"The pound-force has a metric counterpart, less...",What is a very seldom used unit of mass in the...,"{'text': ['slug', 'metric slug', 'metric slug'..."
10568,5737aafd1c456719005744fe,Force,"The pound-force has a metric counterpart, less...",What seldom used term of a unit of force equal...,"{'text': ['kip', 'kip', 'kip', 'kip', 'kip'], ..."
10569,5737aafd1c456719005744ff,Force,"The pound-force has a metric counterpart, less...",What is the seldom used force unit equal to on...,"{'text': ['sthène', 'sthène', 'sthène', 'sthèn..."

In [10]:
eval_dataset_q = eval_dataset.copy()
eval_dataset_q["question"] = np.random.default_rng(seed=388).permutation(eval_dataset["question"].values)

eval_dataset_q

,id,title,context,question,answers
0,56be4db0acb8001400a502ec,Super_Bowl_50,Super Bowl 50 was an American football game to...,What are phytoplankton?,"{'text': ['Denver Broncos', 'Denver Broncos', ..."
1,56be4db0acb8001400a502ed,Super_Bowl_50,Super Bowl 50 was an American football game to...,Who holds an annual International Arts Fair in...,"{'text': ['Carolina Panthers', 'Carolina Panth..."
2,56be4db0acb8001400a502ee,Super_Bowl_50,Super Bowl 50 was an American football game to...,What is the Proto-Germanic adaptation of the n...,"{'text': ['Santa Clara, California', 'Levi's S..."
3,56be4db0acb8001400a502ef,Super_Bowl_50,Super Bowl 50 was an American football game to...,"In August 1994, what Toledo, Ohio affiliate di...","{'text': ['Denver Broncos', 'Denver Broncos', ..."
4,56be4db0acb8001400a502f0,Super_Bowl_50,Super Bowl 50 was an American football game to...,What does Luther write that this life doesn't ...,"{'text': ['gold', 'gold', 'gold'], 'answer_sta..."
...,...,...,...,...,...
10565,5737aafd1c456719005744fb,Force,"The pound-force has a metric counterpart, less...",What was Edison's reply as to what Tesla didn'...,"{'text': ['kilogram-force', 'pound-force', 'ki..."
10566,5737aafd1c456719005744fc,Force,"The pound-force has a metric counterpart, less...",What award was given to Corliss?,"{'text': ['kilopond', 'kilopond', 'kilopond', ..."
10567,5737aafd1c456719005744fd,Force,"The pound-force has a metric counterpart, less...",What is the highest point of the Rhine basin c...,"{'text': ['slug', 'metric slug', 'metric slug'..."
10568,5737aafd1c456719005744fe,Force,"The pound-force has a metric counterpart, less...",What language is spoken in Kenya?,"{'text': ['kip', 'kip', 'kip', 'kip', 'kip'], ..."
10569,5737aafd1c456719005744ff,Force,"The pound-force has a metric counterpart, less...",Whic Carolina Panthers running back was waived?,"{'text': ['sthène', 'sthène', 'sthène', 'sthèn..."

In [11]:
eval_dataset_qs = datasets.Dataset.from_pandas(eval_dataset_q)

eval_dataset_qs

Dataset({
    features: ['id', 'title', 'context', 'question', 'answers'],
    num_rows: 10570
})

In [28]:
vocab = []
with open("../models/model_init/vocab.txt", encoding="utf-8") as f:
    for line in f.readlines():
        vocab.append(line.strip())

len(vocab)

30522

In [34]:
eval_dataset["gold_answer"] = eval_dataset["answers"].apply(lambda d: d["text"][0])

eval_dataset

,id,title,context,question,answers,gold_answer
0,56be4db0acb8001400a502ec,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team represented the AFC at Super Bo...,"{'text': ['Denver Broncos', 'Denver Broncos', ...",Denver Broncos
1,56be4db0acb8001400a502ed,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team represented the NFC at Super Bo...,"{'text': ['Carolina Panthers', 'Carolina Panth...",Carolina Panthers
2,56be4db0acb8001400a502ee,Super_Bowl_50,Super Bowl 50 was an American football game to...,Where did Super Bowl 50 take place?,"{'text': ['Santa Clara, California', 'Levi's S...","Santa Clara, California"
3,56be4db0acb8001400a502ef,Super_Bowl_50,Super Bowl 50 was an American football game to...,Which NFL team won Super Bowl 50?,"{'text': ['Denver Broncos', 'Denver Broncos', ...",Denver Broncos
4,56be4db0acb8001400a502f0,Super_Bowl_50,Super Bowl 50 was an American football game to...,What color was used to emphasize the 50th anni...,"{'text': ['gold', 'gold', 'gold'], 'answer_sta...",gold
...,...,...,...,...,...,...
10565,5737aafd1c456719005744fb,Force,"The pound-force has a metric counterpart, less...",What is the metric term less used than the New...,"{'text': ['kilogram-force', 'pound-force', 'ki...",kilogram-force
10566,5737aafd1c456719005744fc,Force,"The pound-force has a metric counterpart, less...",What is the kilogram-force sometimes reffered ...,"{'text': ['kilopond', 'kilopond', 'kilopond', ...",kilopond
10567,5737aafd1c456719005744fd,Force,"The pound-force has a metric counterpart, less...",What is a very seldom used unit of mass in the...,"{'text': ['slug', 'metric slug', 'metric slug'...",slug
10568,5737aafd1c456719005744fe,Force,"The pound-force has a metric counterpart, less...",What seldom used term of a unit of force equal...,"{'text': ['kip', 'kip', 'kip', 'kip', 'kip'], ...",kip
10569,5737aafd1c456719005744ff,Force,"The pound-force has a metric counterpart, less...",What is the seldom used force unit equal to on...,"{'text': ['sthène', 'sthène', 'sthène', 'sthèn...",sthène

In [39]:
passage_answers = eval_dataset.groupby("context")["gold_answer"].apply(list)

In [109]:
def randomize_passage(passage, answers):
    passage_split = passage.split(" ")
    answers_split = [answer.split(" ") for answer in answers]
    random.shuffle(answers_split)
    indices = [0]

    for answer in answers_split:
        indices.append(indices[-1] + len(answer))
    
    passage_random = list(chain.from_iterable(answers_split))

    while len(passage_random) < len(passage_split):
        insert_slot = random.choice(range(len(indices)))
        passage_random.insert(indices[insert_slot], random.choice(vocab))
        for i in range(insert_slot + 1, len(indices)):
            indices[i] += 1
    
    return " ".join(passage_random)

In [96]:
eval_dataset[eval_dataset["context"] == passage_answers.index[0]]

# Find answers associated with each passage and randomize them one by one probably

,id,title,context,question,answers,gold_answer
3886,5725c604271a42140099d185,Apollo_program,Seamans' establishment of an ad-hoc committee...,Who led the committee established by Seaman?,"{'text': ['Nicholas E. Golovin', 'Nicholas E. ...",Nicholas E. Golovin
3887,5725c604271a42140099d186,Apollo_program,Seamans' establishment of an ad-hoc committee...,When was this committee by Seaman established?,"{'text': ['July 1961', '1961', '1961', 'July 1...",July 1961
3888,5725c604271a42140099d187,Apollo_program,Seamans' establishment of an ad-hoc committee...,Which NASA faction came around first to suppor...,"{'text': ['Manned Spacecraft Center', 'Manned ...",Manned Spacecraft Center
3889,5725c604271a42140099d188,Apollo_program,Seamans' establishment of an ad-hoc committee...,Who was hired to be the deputy director of the...,"{'text': ['Joseph Shea', 'Joseph Shea,', 'Jose...",Joseph Shea
3890,5725c604271a42140099d189,Apollo_program,Seamans' establishment of an ad-hoc committee...,Which NASA location came around last to the id...,"{'text': ['Marshall Space Flight Center', 'Mar...",Marshall Space Flight Center

In [110]:
random.seed(388)
random_passages = []
for passage in eval_dataset["context"]:
    random_passages.append(randomize_passage(passage, passage_answers[passage]))

In [118]:
eval_dataset_p = eval_dataset.copy()

eval_dataset_p["context"] = pd.Series(random_passages)
eval_dataset_p = eval_dataset_p.drop("gold_answer", axis=1)

In [119]:
eval_dataset_p

,id,title,context,question,answers
0,56be4db0acb8001400a502ec,Super_Bowl_50,yields bernard American Football Conference sa...,Which NFL team represented the AFC at Super Bo...,"{'text': ['Denver Broncos', 'Denver Broncos', ..."
1,56be4db0acb8001400a502ed,Super_Bowl_50,serie masterpiece ##t Denver Broncos dancing d...,Which NFL team represented the NFC at Super Bo...,"{'text': ['Carolina Panthers', 'Carolina Panth..."
2,56be4db0acb8001400a502ee,Super_Bowl_50,"February 7, 2016 tertiary 2015 ""golden anniver...",Where did Super Bowl 50 take place?,"{'text': ['Santa Clara, California', 'Levi's S..."
3,56be4db0acb8001400a502ef,Super_Bowl_50,"aimee reich ""golden anniversary"" true indeed S...",Which NFL team won Super Bowl 50?,"{'text': ['Denver Broncos', 'Denver Broncos', ..."
4,56be4db0acb8001400a502f0,Super_Bowl_50,"February 7, 2016 attractions ##horse February ...",What color was used to emphasize the 50th anni...,"{'text': ['gold', 'gold', 'gold'], 'answer_sta..."
...,...,...,...,...,...
10565,5737aafd1c456719005744fb,Force,eighteenth tristan ᅳ unfit contestant wines ca...,What is the metric term less used than the New...,"{'text': ['kilogram-force', 'pound-force', 'ki..."
10566,5737aafd1c456719005744fc,Force,enrique toby ##onne unwilling rattling influen...,What is the kilogram-force sometimes reffered ...,"{'text': ['kilopond', 'kilopond', 'kilopond', ..."
10567,5737aafd1c456719005744fd,Force,cassie translating breton ##islaus identical m...,What is a very seldom used unit of mass in the...,"{'text': ['slug', 'metric slug', 'metric slug'..."
10568,5737aafd1c456719005744fe,Force,commonplace movie mississippi twelfth ##oso ##...,What seldom used term of a unit of force equal...,"{'text': ['kip', 'kip', 'kip', 'kip', 'kip'], ..."
10569,5737aafd1c456719005744ff,Force,##ed 13 plump cupboard jenks denounced ##ading...,What is the seldom used force unit equal to on...,"{'text': ['sthène', 'sthène', 'sthène', 'sthèn..."

In [122]:
eval_dataset_ps = datasets.Dataset.from_pandas(eval_dataset_p)

eval_dataset_ps

Dataset({
    features: ['id', 'title', 'context', 'question', 'answers'],
    num_rows: 10570
})